### ISSUE TITLE
模板格式问题

### ISSUE THREAD

**Issue by wanghuzhen** [jinyiliu/bnu-thesis-template#2]
您好，模板编译出的pdf在每章节第一页会缺少页眉，此外在参考文献以及学术成果部分的第一页也会出现这个现象。请问这是正常的么？还是编译问题？谢谢！！！
![image](https://user-images.githubusercontent.com/37537124/219032425-303c6015-743d-4c4e-9596-3b724bbdbb61.png)
以下是第二页
![image](https://user-images.githubusercontent.com/37537124/219032518-5575ac4c-9ed3-4d97-ada5-5d00219e3748.png)

**Comment by jinyiliu** [comment]
是正常的，因为我记得对章节第一页、参考文献和学术成果没有页眉的要求，没问题的！

**Comment by wanghuzhen** [comment]
好的，谢谢！！！
